---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hibik.
--- DateTime: 4/23/2022 11:01 AM
---
local Utils = {}
local dissectionTools = {"KitchenKnife", "HuntingKnife", "Scalpel"}
local properDissectionTools = {"Scalpel", nil}

local function has_value (tab, val)
    for index, value in ipairs(tab) do
        if value == val then
            return true
        end
    end

    return false
end

function Utils.IsSterilizedBandage(item)
    print(item:getType())
    return item:getType() == "AlcoholBandage"
end

function Utils.IsDissectionTool(item)
    return has_value(dissectionTools, item:getType())
end

function Utils.IsProperDissectionTool(item)
    return has_value(properDissectionTools, item:getType())
end

function Utils.CanDissect(player)
    print("Can Dissect? Perk Lvl: "..player:getPerkLevel(Perks.Doctor))
    return player:getPerkLevel(Perks.Doctor) < 3
end

function Utils.CanBasicFirstAid(player)
    local perkLevel = player:getPerkLevel(Perks.Doctor)
    print(perkLevel)
    if perkLevel and perkLevel > 1 and perkLevel < 5 then return true end
end

function Utils.DamageTool(player, item)
    if not Utils.IsProperDissectionTool(item) then
        player:Say(getText("UI_BFA_Scalpel_Better"))
        item:setCondition(item:getCondition() - 1);
    end
end

return Utils