---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hibik.
--- DateTime: 4/23/2022 11:01 AM
---
local Utils = {}
local dissectionTools = {"KitchenKnife", "HuntingKnife", "Scalpel"}
local properDissectionTools = {"Scalpel", nil}

local function has_value (tab, val)
    for index, value in ipairs(tab) do
        if value == val then
            return true
        end
    end

    return false
end

function Utils.IsDissectionTool(item)
    return has_value(dissectionTools, item:getType())
end

function Utils.IsProperDissectionTool(item)
    return has_value(properDissectionTools, item:getType())
end

function Utils.CanDissect(player)
    return player:getPerkLevel(Perks.Doctor) < 3
end

function Utils.CanBasicFirstAid(player)
    return 2 < player:getPerkLevel(Perks.Doctor) < 5
end

return Utils