---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hibik.
--- DateTime: 4/26/2022 12:49 PM
---

require("TimedActions/ISBaseTimedAction")

DissectTimedAction = ISBaseTimedAction:derive("dissectTimedAction")

function DissectTimedAction:isValid() -- Check if the action can be done
    return true;
end

function DissectTimedAction:update() -- Trigger every game update when the action is perform
end

function DissectTimedAction:waitToStart()
    return false;
end

function DissectTimedAction:start()
    self:setActionAnim("RipSheets")
end

function DissectTimedAction:stop() -- Trigger if the action is cancel
    ISBaseTimedAction.stop(self);
end

function DissectTimedAction:perform()
    BFA_OnGiveXP_Dissect(nil, nil, nil, self.character)
    BFA_OnCreate_Damage_Tools({ self.dissectionTool }, nil, self.character)
    self.corpse:getSquare():removeCorpse(self.corpse, false)
    ISBaseTimedAction.perform(self)
end

function DissectTimedAction:new(character, dissectionTool, corpse)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    o.character = character
    o.dissectionTool = dissectionTool
    o.corpse = corpse
    o.stopOnWalk = true;
    o.stopOnRun = true;
    o.stopOnAim = true;
    o.maxTime = 200
    if o.character:isTimedActionInstant() then o.maxTime = 1 end
    return o
end